name: public_speaking_assistant
description: Public Speaking Improvement Assistant application for bachelor's thesis
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.11.0
  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^1.0.1

  # flutter
  flutter_redux: ^0.8.2

  # dart
  redux: ^5.0.0
  redux_epics: ^0.15.0
  rxdart: ^0.26.0
  built_value: ^8.0.3
  built_collection: ^5.0.0
  freezed_annotation: ^0.14.1
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  built_value_generator: any
  freezed: any

flutter:
  uses-material-design: true
